// Generated by scripts/gen_accessory_metrics.py: do not edit.
// Opaque bounding box of each accessory image, in px of its 32x32 grid.

export const ACCESSORY_GRID = 32;

export const ACCESSORY_METRICS = Object.freeze({
  bow: { x0: 1, y0: 8, x1: 31, y1: 29 },
  cone: { x0: 7, y0: 1, x1: 29, y1: 31 },
  crown: { x0: 1, y0: 2, x1: 32, y1: 32 },
  foilhat: { x0: 2, y0: 0, x1: 32, y1: 32 },
  glasses: { x0: 2, y0: 18, x1: 31, y1: 31 },
  halo: { x0: 1, y0: 20, x1: 31, y1: 32 },
  laurel: { x0: 0, y0: 10, x1: 32, y1: 32 },
  medal: { x0: 3, y0: 0, x1: 29, y1: 32 },
  partyhat: { x0: 4, y0: 0, x1: 28, y1: 31 },
  santa: { x0: 2, y0: 0, x1: 32, y1: 32 },
  sock: { x0: 0, y0: 13, x1: 30, y1: 32 },
  witch: { x0: 0, y0: 0, x1: 32, y1: 31 },
});
