#!/usr/bin/env python3
"""Writes core/accessoryMetrics.js: the opaque bounding box of each accessory
image (32x32 px), so that sizes can be set on what is actually drawn rather
than on the image, whatever its margins.

Run it again after redrawing the accessories (gen_ui_sprites.py):
    python3 scripts/gen_accessory_metrics.py
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "extension" / "assets" / "accessories"
TARGET = ROOT / "core" / "accessoryMetrics.js"


def main():
    rows = []
    for path in sorted(SOURCE.glob("*.png")):
        image = Image.open(path).convert("RGBA")
        if image.size != (32, 32):
            raise SystemExit(f"{path.name}: expected 32x32, got {image.size}")
        x0, y0, x1, y1 = image.getchannel("A").point(lambda a: 255 if a > 8 else 0).getbbox()
        rows.append(f"  {path.stem}: {{ x0: {x0}, y0: {y0}, x1: {x1}, y1: {y1} }},")
    TARGET.write_text(
        "// Generated by scripts/gen_accessory_metrics.py: do not edit.\n"
        "// Opaque bounding box of each accessory image, in px of its 32x32 grid.\n\n"
        "export const ACCESSORY_GRID = 32;\n\n"
        "export const ACCESSORY_METRICS = Object.freeze({\n" + "\n".join(rows) + "\n});\n",
        encoding="utf-8",
    )
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(rows)} accessories)")


if __name__ == "__main__":
    main()
